### PR TITLE
feat:add casdoor-uniapp

### PR DESCRIPTION
**Pull request by Beacontownfc**
The **casdoor-uniapp-sdk** has been published, you can use command `npm i casdoor-uniapp-sdk` to install it.

### CODE REVIEW

**Comment by hsluoyz** [comment]
@Beacontownfc fix:

image

**Comment by hsluoyz** [comment]
@xiaobeiswift plz review

**Comment by Beacontownfc** [comment]
> @Beacontownfc fix:
> 
> image

Done

**Review by xiaobeiswift — APPROVED** [review]
ok,plz merge

**Pull request merged**
